services:
  vita:
    image: registry.gitlab.com/monocircuit/platform:develop
    container_name: vita-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
